//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string employee_id { get; set; }
        public string employee_password { get; set; }
        public Nullable<bool> employee_status { get; set; }
        public string employee_name { get; set; }
        public string email_address { get; set; }
        public string phone_number { get; set; }
    }
}
