//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int FooterID { get; set; }
        public string Contain { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> FooterIDType { get; set; }
        public Nullable<int> FooterParentID { get; set; }
        public string Link { get; set; }
        public string Target { get; set; }
    }
}
