//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_items()
        {
            this.Shipments = new HashSet<Shipment>();
        }
    
        public string order_item_id { get; set; }
        public string order_id { get; set; }
        public string product_id { get; set; }
        public Nullable<int> order_item_status_code { get; set; }
        public Nullable<int> order_item_quantity { get; set; }
        public Nullable<float> order_item_price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Ref_Order_Item_Status_Codes Ref_Order_Item_Status_Codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipment> Shipments { get; set; }
    }
}
