//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string payment_id { get; set; }
        public string invoice_number { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<float> payment_amount { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
