//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string product_id { get; set; }
        public string product_type_code { get; set; }
        public string product_name { get; set; }
        public Nullable<float> product_price { get; set; }
        public string product_description { get; set; }
        public string product_size { get; set; }
        public string product_color { get; set; }
        public string product_imge { get; set; }
        public string more_image { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<float> promotionprice { get; set; }
    
        public virtual Ref_Product_Types Ref_Product_Types { get; set; }
    }
}
