//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SHOPEntities : DbContext
    {
        public SHOPEntities()
            : base("name=SHOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Footer> Footers { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Order_items> Order_items { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Ref_Invoice_Status_Codes> Ref_Invoice_Status_Codes { get; set; }
        public virtual DbSet<Ref_Order_Item_Status_Codes> Ref_Order_Item_Status_Codes { get; set; }
        public virtual DbSet<Ref_Order_Status_Codes> Ref_Order_Status_Codes { get; set; }
        public virtual DbSet<Ref_Product_Types> Ref_Product_Types { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
    }
}
